/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './context/**/*.{js,ts,jsx,tsx,mdx}',
    './lib/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'secondary-container': '#571bc1',
        'primary-fixed-dim': '#c0c1ff',
        'inverse-on-surface': '#2e3037',
        'inverse-surface': '#e1e2eb',
        'surface-container-low': '#191c22',
        'on-error-container': '#ffdad6',
        'on-surface': '#e1e2eb',
        'error-container': '#93000a',
        'secondary-fixed-dim': '#d0bcff',
        'outline-variant': '#464554',
        'on-tertiary-fixed': '#002113',
        'tertiary': '#4edea3',
        'outline': '#908fa0',
        'on-primary': '#1000a9',
        'on-primary-fixed-variant': '#2f2ebe',
        'secondary-fixed': '#e9ddff',
        'surface-container-lowest': '#0b0e14',
        'on-primary-container': '#0d0096',
        'on-tertiary': '#003824',
        'on-error': '#690005',
        'on-secondary': '#3c0091',
        'surface-container-highest': '#32353c',
        'on-secondary-fixed': '#23005c',
        'background': '#10131a',
        'surface-container-high': '#272a31',
        'inverse-primary': '#494bd6',
        'on-primary-fixed': '#07006c',
        'on-surface-variant': '#c7c4d7',
        'surface-tint': '#c0c1ff',
        'surface': '#10131a',
        'on-background': '#e1e2eb',
        'tertiary-fixed': '#6ffbbe',
        'tertiary-container': '#00885d',
        'surface-container': '#1d2026',
        'on-secondary-fixed-variant': '#5516be',
        'primary': '#c0c1ff',
        'on-tertiary-fixed-variant': '#005236',
        'tertiary-fixed-dim': '#4edea3',
        'secondary': '#d0bcff',
        'surface-variant': '#32353c',
        'error': '#ffb4ab',
        'on-secondary-container': '#c4abff',
        'surface-bright': '#363940',
        'surface-dim': '#10131a',
        'primary-container': '#8083ff',
        'on-tertiary-container': '#000703',
        'primary-fixed': '#e1e0ff',
        nexus: {
          bg: '#0B0E14',
          surface: '#151922',
          surfaceCard: '#191C24',
          surfaceHover: '#1E232E',
          border: '#252B38',
          indigo: '#6366F1',
          emerald: '#10B981',
          muted: '#8B949E',
          text: '#E6EDF3',
        }
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        sm: '0.25rem',
        md: '0.5rem',
        lg: '0.75rem',
        xl: '1rem',
        '2xl': '1.25rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      spacing: {
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '0.75rem',
        'space-lg': '1.25rem',
        'space-xl': '2rem',
        margin: '1rem',
        gutter: '1rem',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        inter: ['Inter', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
        'body-sm': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
        'headline-xl': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'code-sm': ['JetBrains Mono', 'monospace'],
        'body-md': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'headline-xl-mobile': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'body-sm': ['13px', { lineHeight: '18px', letterSpacing: '0', fontWeight: '400' }],
        'headline-lg': ['24px', { lineHeight: '32px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'label-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.04em', fontWeight: '600' }],
        'headline-xl': ['36px', { lineHeight: '44px', letterSpacing: '-0.025em', fontWeight: '700' }],
        'headline-md': ['18px', { lineHeight: '26px', letterSpacing: '-0.015em', fontWeight: '600' }],
        'label-md': ['13px', { lineHeight: '18px', letterSpacing: '0.01em', fontWeight: '500' }],
        'code-sm': ['12px', { lineHeight: '18px', letterSpacing: '0', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '22px', letterSpacing: '0', fontWeight: '400' }],
        'body-lg': ['16px', { lineHeight: '24px', letterSpacing: '-0.01em', fontWeight: '400' }],
        'headline-xl-mobile': ['28px', { lineHeight: '36px', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
}
